
- name: My first play
  hosts: all
  become: true
  vars:
     ansible_become_password: ""
     ansible_user: ubuntu
  tasks:


  - name: Install nginx
    apt:
      name: nginx
      state: latest
